cluster_name: ray-cluster
min_workers: 1
max_workers: 2
idle_timeout_minutes: 5
provider:
    type: azure
    location: swedencentral
auth:
    ssh_user: bielik
available_node_types:
    worker:
        min_workers: 1
        max_workers: 2
        node_config:
            vm_size: "Standard_NC4as_T4_v3"
            priority: "Spot"
